# Generated by Django 4.1.5 on 2023-01-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(verbose_name='log date time')),
            ],
        ),
    ]
