# Generated by Django 4.1.5 on 2023-01-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceService', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='imgfile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
